### ISSUE TITLE
Setup the CI/CD

### ISSUE THREAD

**Issue by petrvecera** [profiq/swapi-elixir#11]
- Master branch should be automatically deployed to DEV environment 
- On tags/ releases deploy to production 

Triggers
https://github.com/cohstats/coh3-stats/blob/master/.github/workflows/deploy-prod.yml#L5
https://github.com/cohstats/coh3-stats/blob/master/.github/workflows/deploy.yml#L5

**Comment by dhrdlicka** [comment]
Added in 574f5aecd941445c21edca7e64bf301f6aad465e
